server:
  port: 8080

spring:
  application:
    name: FarmStore

  datasource:
    url: jdbc:postgresql://localhost:5431/FarmStore
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration